name: 'Generate Env File'
description: 'Generate Env File'
inputs:
  variables:
    required: true
runs:
  using: "composite"
  steps: 
     - 
      name: Generate Env File
      id: generate_file
      shell: bash
      run: |
        touch /tmp/env
        t=${{ inputs.variables }}
        echo $t
        sentence=${t//,/$'\n'}  # change the semicolons to white space
        for envname in $sentence
        do
            envvalue=$(printf '%s\n' "${!envname}");
            echo "$envname=$envvalue" >> /tmp/env
        done
