version: '3.8'

services:
  nginx:
    container_name: nginx-capdrop
    restart: unless-stopped
    image: nginx:latest-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data_delete:/application/data:rw
    environment:
      - TLS_MODE=acme
      - FORCE_TLS=true
      - ACME_MAIL=your-email@example.com
      - ACME_SERVER=letsencrypt
      - ACME_ECC=true
      - ACME_KEYLENGTH=ec-384
      - OUTPUT_FORMAT=human
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /application/run:size=2M,uid=1001,gid=1001,mode=0770,noexec,nosuid,nodev
      - /application/tmp:size=32M,uid=1001,gid=1001,mode=0770,noexec,nosuid,nodev
      - /var/lib/nginx/logs:size=8M,uid=1001,gid=1001,mode=0755,noexec,nosuid,nodev
      - /application/bin/acmesh/ca/:size=8M,uid=1001,gid=1001,mode=0755,noexec,nosuid,nodev
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge