name: 'Build Docker Images'
description: 'Build Docker Images for linux/arm/v6 and linux/amd64'
runs:
  using: "composite"
  steps: 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        uses: nick-invision/persist-action-data@v1
        with:
          retrieve_variables: BUILD_DATE,VERSION,GUTHASH,TAGS
      - 
        run: |
          echo $BUILD_DATE
          echo $VERSION
          echo $GITHASH
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v6,linux/amd64
          push: true
          tags: $TAGS
          build-args: |
            BUILD_DATE=$BUILD_DATE
            VCS_REF=$GITHASH
            VERSION=$VERSION
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
