server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	server_name localhost;

	http2 on;
	
	ssl_certificate	 /application/data/certs/localhost.pem;
	ssl_certificate_key /application/data/certs/localhost.key;

	include /application/data/snippets/gzip.conf;
	include /application/data/snippets/header.conf;
	include /application/data/snippets/tls.conf;
	include /application/data/snippets/caching_header.conf;	
	include /application/data/snippets/ratelimit.conf;
	
	location / {
		root   /application/data/webroot;
		index  index.html index.htm;
		try_files $uri $uri/ $uri.html $uri.htm =404;
	}
	
	include /application/data/locations/*.conf;

}