server {
	listen 8080 default_server;
	listen [::]:8080 default_server;
	server_name localhost; 
	
	include /application/config/snippets/ratelimit.conf;

	location / {
		return 301 https://$host$request_uri;
	}
}