#!/bin/sh
set -e

L_GIT_SHA1="${GIT_SHA1}"
L_VERSION=$(head -n 1 ./CHANGELOG)

L_INTVERSION=$(curl -vs https://pkgs.alpinelinux.org/package/v3.11/main/x86_64/nginx 2>&1 | grep -oh  "[[:digit:]]\.[[:digit:]]\{1,2\}\.[[:digit:]]\{1,2\}-r[0-9]\{1,2\}")

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=${L_GIT_SHA1} \
             --build-arg VERSION=${L_VERSION} \
             --build-arg INTVERSION=${L_INTVERSION} \
             -t $IMAGE_NAME .
