#!/bin/bash

set -e

L_SOURCE_BRANCH="${SOURCE_BRANCH}"
L_GIT_SHA1="${GIT_SHA1}"
L_VERSION=$(head -n 1 ./CHANGELOG)
L_VERSIONSUFFIX=$(echo $L_VERSION| cut -d '-' -f 2)
L_MINORVERSION="${L_VERSION%.*}-${L_VERSIONSUFFIX}"

if [ "$L_SOURCE_BRANCH" = "master" ]; then
  git tag "version-$L_VERSION" "$L_GIT_SHA1"
  git push origin --tags
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_VERSION}
  docker push ${DOCKER_REPO}:${L_VERSION}
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_MINORVERSION}
  docker push ${DOCKER_REPO}:${L_MINORVERSION}
fi
