#!/bin/bash

set -e

L_SOURCE_BRANCH="${SOURCE_BRANCH}"
L_GIT_SHA1="${GIT_SHA1}"
L_VERSION=$(head -n 1 ./CHANGELOG)
L_VERSIONSUFFIX=""

echo "Building Branch $L_SOURCE_BRANCH ($L_GIT_SHA1), how lovely..."

if [[ $L_VERSION == *"-"* ]]; then
        L_VERSIONSUFFIX="-$(echo $L_VERSION| cut -d '-' -f 2)"
fi
L_MINORVERSION="${L_VERSION%.*}${L_VERSIONSUFFIX}"

L_INTVERSION=$(curl -vs https://pkgs.alpinelinux.org/package/v3.11/main/x86_64/nginx 2>&1 | grep -oh  "[[:digit:]]\.[[:digit:]]\{1,2\}\.[[:digit:]]\{1,2\}-r[0-9]\{1,2\}")
L_INTVERSIONSUFFIX=""

if [[ $L_INTVERSION == *"-"* ]]; then
        L_INTVERSIONSUFFIX="-$(echo $L_INTVERSION | cut -d '-' -f 2)"
fi
L_INTMINORVERSION="${L_INTVERSION%.*}"

L_GITTAG="version-$L_INTVERSION-L_VERSION"

echo "Tags: $L_INTVERSION-$L_VERSION, $L_INTVERSION, $L_VERSION, $L_MINORVERSION, $L_INTMINORVERSION-$L_VERSION, $L_INTMINORVERSION, $L_INTMINORVERSION-$L_MINORVERSION"

if [ "$L_SOURCE_BRANCH" = "master" ]; then
  git tag "$L_GITTAG" "$L_GIT_SHA1"
  git push origin --tags
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_INTVERSION}-${L_VERSION}
  docker push ${DOCKER_REPO}:${L_INTVERSION}-${L_VERSION}
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_INTVERSION}
  docker push ${DOCKER_REPO}:${L_INTVERSION}
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_VERSION}
  docker push ${DOCKER_REPO}:${L_VERSION}
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_MINORVERSION}
  docker push ${DOCKER_REPO}:${L_MINORVERSION}
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_INTMINORVERSION}-${L_VERSION}
  docker push ${DOCKER_REPO}:${L_INTMINORVERSION}-${L_VERSION}
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_INTMINORVERSION}
  docker push ${DOCKER_REPO}:${L_INTMINORVERSION}
  
  docker tag $IMAGE_NAME ${DOCKER_REPO}:${L_INTMINORVERSION}-${L_MINORVERSION}
  docker push ${DOCKER_REPO}:${L_INTMINORVERSION}-${L_MINORVERSION}
fi
