#!/bin/bash

set -e

L_SOURCE_BRANCH="${SOURCE_BRANCH}"
L_GIT_SHA1="${GIT_SHA1}"
L_VERSION=$(head -n 1 ./CHANGELOG)
L_VERSIONSUFFIX=$(echo $L_VERSION| cut -d '-' -f 2)
L_MINORVERSION="${L_VERSION%.*}-${L_VERSIONSUFFIX}"

compgen -c

echo "Building Branch $L_SOURCE_BRANCH ($L_GIT_SHA1)"

SOFTVERSION=$(wget https://pkgs.alpinelinux.org/package/edge/main/x86_64/nginx -O - | grep -oP '(?<=<a class="hint--right text-danger" aria-label="Flagged: .{19}" href="#">)[^<]*')

echo "SOFTVERSION = $SOFTVERSION"

if [ "$L_SOURCE_BRANCH" = "master" ]; then
  echo "Oh we are building master..."
  echo "This version $L_VERSION is Part of series $L_MINORVERSION"
  if git rev-parse "version-$L_VERSION" >/dev/null 2>&1; then
    echo "Version $L_VERSION already exists";
    exit 1;
  fi
fi
