name: "Generate Versions"
description: "Extract Versions from changelog"
inputs:
  VERSION:
    required: true
  VERSION_MINOR:
    required: true
  branch:
    required: true
    default: true
  isWeekly:
    required: true
    default: false
  vendorVersion:
      required: false
outputs:
  TAGS:
    description: "TAGS"
    value: ${{ steps.generate_tags.outputs.TAGS }}
runs:
  using: "composite"
  steps:
    - name: Generate Tags
      id: generate_tags
      shell: bash
      run: |
        TAGS=""
        IMAGENAME="$IMAGE_NAME"
        if [ ${{ inputs.branch }} = 'master' ] ; then
            if [ ${{ inputs.isWeekly }} = true ] ; then
             echo 'Generate Weekly Tags'
             TAGS=`echo -e "$IMAGENAME:latest-weekly,$IMAGENAME:$VERSION-weekly,$IMAGENAME:$VERSION_MINOR-weekly"`
            else 
              echo 'Generate Master Tags'
              TAGS=`echo -e "$IMAGENAME:latest,$IMAGENAME:$VERSION,$IMAGENAME:$VERSION_MINOR"`
            fi
            if [ ! -z "${{ inputs.vendorVersion }}" ] ; then
              TAGS="$TAGS,$IMAGENAME:${{ inputs.vendorVersion }}"
            fi
        elif [ ${{ inputs.branch }} = 'dev' ] ; then
           TAGS=`echo -e "$IMAGENAME:latest-dev,$IMAGENAME:$VERSION-dev,$IMAGENAME:$VERSION_MINOR-dev"`
        fi
        echo ">>$TAGS<<"
        echo "::set-output name=TAGS::$TAGS"
        echo "::set-env name=TAGS::$TAGS"
