name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          mkdir /tmp/versions && touch /tmp/versions/env.sh && chmod +x /tmp/versions/env.sh
          VERSION=$(head -n 1 ./CHANGELOG)
          VERSION_RELEASE=$(echo $VERSION | cut -d '-' -f 2 -s)
          VERSION_PATCH=${VERSION%-*}
          VERSION_MINOR=${VERSION_PATCH%.*}
          VENDORVERSION=$(curl -vs https://pkgs.alpinelinux.org/package/v3.11/main/x86_64/nginx 2>&1 | grep -o -h -m 1 "[[:digit:]]\.[[:digit:]]\{1,2\}\.[[:digit:]]\{1,2\}-r[0-9]\{1,2\}")
          VENDORVERSION_RELEASE=$(echo $VENDORVERSION | cut -d '-' -f 2 -s)
          VENDORVERSION_PATCH=${VENDORVERSION%-*}
          VENDORVERSION_MINOR=${VENDORVERSION_PATCH%.*}
          GITTAG="version-$VERSION-$VENDORVERSION"
          echo -e "echo \"::set-env name=VERSION::$VERSION\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=VERSION_RELEASE::$VERSION_RELEASE\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=VERSION_PATCH::$VERSION_PATCH\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=VERSION_MINOR::$VERSION_MINOR\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=VENDORVERSION::$VENDORVERSION\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=VENDORVERSION_RELEASE::$VENDORVERSION_RELEASE\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=VENDORVERSION_PATCH::$VENDORVERSION_PATCH\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=VENDORVERSION_MINOR::$VENDORVERSION_MINOR\"" >> /tmp/versions/env.sh
          echo -e "echo \"::set-env name=GITTAG::$GITTAG\"\n" >> /tmp/versions/env.sh
      - name: Upload Version Artefact
        uses: actions/upload-artifact@v1
        with:
          name: versions
          path: /tmp/versions

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - name: Download Version Artefact
        uses: actions/download-artifact@v1
        with:
          name: versions
          path: /tmp/versions
      - name: Import Variables
        run: bash /tmp/versions/env.sh
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Check if Build needed
        run: |
          exit 78
