name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image
  VERSION: foo

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
      - uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          touch /tmp/versions
          VERSION=$(head -n 1 ./CHANGELOG)
          echo -e "VERSION=$VERSION" >> /tmp/versions
      - name: Upload Version Artefact
      - uses: actions/upload-artifact@v1
        with:
          name: versions
          path: /tmp/versions

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
      - uses: actions/checkout@v2
      - name: Download Version Artefact
      - uses: actions/download-artifact@v1
        with:
          name: versions
          path: /tmp/versions
      - name: Show Versions
        run: |
          cat /tmp/versions
