name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image
  VENDOR_VERSION: unknown
  VERSION: unknown

jobs:
  versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          $TEMP=´head -n 1 ./CHANGELOG´
          echo "TEMP=$TEMP"
          echo "::set-env name=VERSION::$TEMP"
          echo "VERSION=${{ env.VERSION }}"

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: echo "VERSION=${{ env.VERSION }}"
