name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image
  VERSION: foo

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          VERSION=$(head -n 1 ./CHANGELOG); echo VERSION=$VERSION
          echo "::set-env name=VERSION::$VERSION"
      - name: VERSION
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "VERSION=$VERSION" 

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: printenv
        run: printenv
      - name: Build image
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "VERSION=$VERSION" 
