name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image

jobs:
  versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          export APK_NAME="release_$(date +'%Y-%m-%d')"
          echo "::set-env name=APK_NAME::$APK_NAME"
          echo "APK_NAME=$APK_NAME"

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: echo "Build image ${{ env.APK_NAME }}"
