name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image
  VENDOR_VERSION: unknown
  VERSION: unknown

jobs:
  versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          TEST=$(head -n 1 ./CHANGELOG); echo TEST=$TEST
          echo TEST=$TEST
          echo "::set-env name=VERSION2::$(head -n 1 ./CHANGELOG)"
          echo "VERSION2=${{ env.VERSION2 }}"

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: echo "VERSION2=${{ env.VERSION2 }}"
