name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image

jobs:
  versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          TEST=$(head -n 1 ./CHANGELOG); echo TEST=$TEST
          echo TEST=$TEST
          envman add --key VERSION --value "$TEST"
          echo "VERSION=${{ env.VERSION }}"
          echo "VERSION=$VERSION"
          echo "::set-env name=ABC::yellow"
      - name: ABC
        run: |
          echo "ABC=${{ env.ABC }}"
          echo "ABC=$ABC" 

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "VERSION=$VERSION"

