name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image
  VERSION: foo

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.1.0
      - name: Get Version
        run: |
          mkdir /tmp/versions && touch /tmp/versions/env.sh && chmod +x /tmp/versions/env.sh
          VERSION=$(head -n 1 ./CHANGELOG)
          echo -e "echo \"::set-env name=VERSION::$VERSION\"\n" >> /tmp/versions/env.sh
      - name: Upload Version Artefact
        uses: actions/upload-artifact@v1
        with:
          name: versions
          path: /tmp/versions

  push:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Download Version Artefact
        uses: actions/download-artifact@v1
        with:
          name: versions
          path: /tmp/versions
      - name: Import Variables
        run: |
          ./tmp/versions/env.sh
          echo "VERSION: $VERSION"
      - name: Import Variables 2
        run: |
          echo "VERSION: $VERSION"
